clover-conversion/README.md
Added `/Library/Application\ Support/clover` folder to remove.
I just found out that there is a `Clover Updater` that keeps asking me to update my clover even after I have removed the preference pane and switched to OpenCore 😞
=> Add clover updater folder to remove.

AMD/zen.md
There is a typo in amd/zen. In the guide it is described as `ProtectMemoryRegion`, however it should be `ProtectMemoryRegions`.
=> fix typo in amd/zen

post-install/iservices.md
In Catalina zsh is default over bash and the old commands don't work. These are generic and work on both
=> Updated terminal commands for zsh compatibility

AMD/fx.md, AMD/zen.md, clover-conversion/clover-patch.md, extras/spoof.md, installer-guide/linux-install.md, installer-guide/mac-install.md, installer-guide/winblows-install.md
Currently if link is in the header, it's not clickable for `Installer guides` - [Mac](https://dortania.github.io/OpenCore-Desktop-Guide/installer-guide/mac-install.html#now-with-all-this-done-head-to-setting-up-the-efi-to-finish-up-your-work), [Windows](https://dortania.github.io/OpenCore-Desktop-Guide/installer-guide/winblows-install.html#now-with-all-this-done-head-to-setting-up-the-efi-to-finish-up-your-work) and [Linux](https://dortania.github.io/OpenCore-Desktop-Guide/installer-guide/linux-install.html#now-with-all-this-done-head-to-setting-up-the-efi-to-finish-up-your-work) guides.
Same behaviour in Firefox 77.0.1, Chrome 83.0.4103.97 and Safari 13.1.1 (15609.2.9.1.2).
Keep original style and split header to header and text, so link would be clickable again.
Also, few suggested …
=> Fix non-clickable 'Setting up the EFI' link

AMD/fx.md, AMD/zen.md, SUMMARY.md, config-HEDT/broadwell-e.md, config-HEDT/haswell-e.md, config-HEDT/skylake-x.md, config.plist/coffee-lake.md, config.plist/comet-lake.md, config.plist/haswell.md, config.plist/ivy-bridge.md, config.plist/kaby-lake.md, config.plist/skylake.md, installer-guide/opencore-efi.md, ktext.md
A follow-up PR to #72.
Split header and text to make links clickable.
Make ACPI link external.
Would be happy to adjust if necessary.
=> Split header and text to make links clickable

extras/spoof.md
I have done some additional investigation into GPU pass through. There are hardware limitations and more drawbacks than originally thought. I encourage anyone to take a look at this themselves. Also added a few missing periods and adjusted a sentence run on.
GSync only works if the display is connected to the GPU. Even though you see compatible, you will not be using it if you use passthrough to the IGPU. https://www.tomshardware.com/reviews/nvidia-gsync-monitor-glossary-definition-explained,6008.html
Settings can't be opened. Self explanatory. But here is an image https://i.imgur.com/uXUApuB.png
In my testing, I lost about ~6 fps with pass through. During a more intense draw, I lost up to ~10. Ouch. I suspect this loss would be less if someone has a more powerful system than I.
Input …
=> Further clarify GPU feature and fix type.

config.plist/README.md
Multiple people in the AMD Discord have been confused and have just been running `Clean Snapshot` without opening the sample config (which obviously leaves them without a lot of needed sections)
https://discordapp.com/channels/249992304503291905/263757191608139779/725396805038243871 read from here down to see discussion about why
=> Add instruction to open config in ProperTree

package-lock.json, package.json
Table content on [this page](https://dortania.github.io/OpenCore-Install-Guide/terminology.html) is very crowded, and the code backgrounds are overlapping. I recently opened a pull request on the original theme repo to fix the line height issue with tables. A simple version bump should fix this.
=> Bump vuepress-theme-succinct version to fix table style

extras/big-sur/README.md
Removing the non-nic plugin kext solves wifi hardware detection on 94352Z/HMB
=> [Big Sur] Add AirportBrcmInjector Plugin Known Issue

troubleshooting/troubleshooting.md
In the section **"Waiting for Root Device" or Prohibited Sign error**, I added a bullet point explaining that it might help to move the USB from a 3.x port to a 2.0 port.
This solved it for me when I was working on a Dell Optiplex 7010, so I figured it might be worthwhile to add it to the troubleshooting guide.
=> Add note about USB 3 vs 2

dictionary/dictionary.txt, ktext.md, troubleshooting/extended/opencore-issues.md
if use old saying, Ivy 's i3 and celeron will use HFSPlus.efi, finally get a black screen before picker
=> HfsPlusLegacy.efi for ivy-bridge i3 or celeron

extras/big-sur/README.md
- OpenCore 0.6.0 is released, so you don't need the latest commit anymore
- The Public Beta is out
- Some minor fixes
=> Update Big Sur installation instructions

ktext.md
RealtekRTL8111 2.3.0 has seen stability issues with OpenCore 0.6.2. A workaround while waiting for Mieze to fix this issue is to downgrade to RealtekRTL8111 to version 2.2.2 or downgrade OpenCore to version 0.6.1 (an issue has been opened about this but it does not look like Mieze is going to fix this issue any time soon)
=> Notify users with RealtekRTL8111 issue

config.plist/sandy-bridge.md
Altered text to 6th generation motherboard under "DeviceProperties" section, where guide was wrongly referring to 7th generation motherboard.
=> Fixed typo where referring to motherboard generation

.vuepress/styles/index.styl
ec875ef: This commit removes horizontal scrollbar by `overflow-x: hidden;`. However, vertical scrollbar remains set to the `scroll` value.
af448c0: Thanks to @Mirdukkk for researching and solving this issue. As Mirdukkk researched, the body was not fully stretched.
<details>
<summary>Screenshots</summary>
Two fixes are shown in both dark and light themes:
Removing horizontal scrollbar in html does not affect to content with scrollbars (weird wording of the sentence, see screenshot below):
As you can see, the scrollbar remains. 
</details>
=> Some technical fixes

why-oc.md
The link I'm proposing changing does not work at https://dortania.github.io/OpenCore-Install-Guide/why-oc.html.
Though I have not been able to test re-building the pages and viewing and checking, the required link seems to be what I've updated it to here.
=> why-oc.md: fix broken link

why-oc.md
I changed the "Apple's servers directly" link to point to macrecovery.py instead of GibMacOS as that is what the guide uses now. It will be clearer, and newcomers will not wonder why it is pointing to GibMacOS when the tool is not even mentioned in the guide.
=> Changed GibMacOS link

config-HEDT/broadwell-e.md, config-HEDT/haswell-e.md, config-HEDT/ivy-bridge-e.md, config-HEDT/nehalem.md, config-HEDT/skylake-x.md, config-laptop.plist/arrandale.md, config-laptop.plist/broadwell.md, config-laptop.plist/coffee-lake-plus.md, config-laptop.plist/coffee-lake.md, config-laptop.plist/haswell.md, config-laptop.plist/icelake.md, config-laptop.plist/ivy-bridge.md, config-laptop.plist/kaby-lake.md, config-laptop.plist/sandy-bridge.md, config-laptop.plist/skylake.md, config.plist/clarkdale.md, config.plist/coffee-lake.md, config.plist/comet-lake.md, config.plist/haswell.md, config.plist/ivy-bridge.md, config.plist/kaby-lake.md, config.plist/sandy-bridge.md, config.plist/skylake.md, dictionary/dictionary.txt, extras/big-sur/README.md, installer-guide/linux-install.md, installer-guide/mac-install-recovery.md, installer-guide/mac-install.md, installer-guide/winblows-install.md, troubleshooting/extended/kernel-issues.md
To be merged when 11.3 releases to the public.
Note: macOS 11.2.1 InstallAssistant link is still uploading for those who recieve 404s
=> Add 11.3+ note for XhciPortLimit

find-hardware.md
Very tiny change in the Linux section of the "Finding hardware" page. No files need to be concatenated and `grep` takes file names as argument so it's [not a very useful use of cat](http://www.smallo.ruhr.de/award.html) ;)
=> Removed unneeded use of `cat`

AMD/fx.md, AMD/zen.md
MacPro6,1 and iMac14,2 aren't good practice on AMD systems. MacPro6,1 has no functional benefit over MacPro7,1 with GCN cards, and iMac SMBIOSes expect an Intel integrated GPU, which obviously AMD systems don't have.
I also replaced the example with MacPro7,1, as that's slightly better than iMacPro1,1 (although in practice it probably doesn't matter). MacPro7,1 doesn't require ACPI renames for native USB maps and it has better support under the hood for dedicated GPUs.
=> AMD SMBIOS info fixup

dictionary/dictionary.txt, extras/monterey.md, ktext.md
Hi guys,
I am not the only one having this [issue](https://github.com/khronokernel/SmallTree-I211-AT-patch/issues/3).
So it would make sense probably to update the guide.
P.s. AppleIGB partially solves the issue but it has it's own problems.
=> I211 on macOS 12 Montery doesn't work with SmallTreeIntel82576 kext

extras/monterey.md
Add the updated boot-arg to prevent freezes on macOS 12.3+
=> Add info for enabling I225-V on 12.3+

troubleshooting/extended/kernel-issues.md
Now opens the correct Github repo with the README.md file instead of giving an 404 Github error.
=> update url to amd patches

config.plist/README.md
Just a small fix on the config.plist tutorial to make it clearer what the name of the sample file is
=> Correct name of current Sample.plist file

installer-guide/mac-install.md
I ran into this issue trying to create a bootable High Sierra USB on my M2 MacBook, found [a fix that worked for me](https://forums.macrumors.com/threads/you-cant-use-an-m1-mac-to-create-bootable-pre-bigsur-macos-installers.2283560/) and thought it should probably be in the install guide.
=> fix: apple silicon bootable USB for older MacOS versions

troubleshooting/extended/post-issues.md
This is due to CorpNewt himself saying that the CsrDecode tool is outdated.
=> Replace CsrDecode in the "Disabling SIP" section with BitmaskDecode

extras/smbios-support.md
In the iBook - PowerPC section the PowerBook 2,2's SMBIOS is labeled as being from "Late 20000"!  I don't know if you know something that I don't but I don't think that's correct.  
Summary: Change PowerBook 2,2's SMBIOS year to Late 2000.
=> Fix a typing error

AMD/fx.md, AMD/zen.md
Since macOS 13.3, there has been a fourth core count patch added to the AMD Vanilla Patches. This PR adds it to the guide.
=> Update AMD OS X Vanilla Kernel Patches for 13.3

config-laptop.plist/coffee-lake-plus.md, config-laptop.plist/coffee-lake.md, config-laptop.plist/icelake.md, config-laptop.plist/kaby-lake.md, config-laptop.plist/skylake.md
Added `ProtectMemoryRegions` under ACPI -> Booter -> Quirks to fix shutdown and restart on coreboot UEFI firmware that Chromebooks utilize and  `-igfxnotelemetryload` to fix iGPU acceleration on 10.15 and up.
=> Add Chromebook specific properties to Skylake and newer config.plist's

config-HEDT/broadwell-e.md, config-HEDT/haswell-e.md, config-HEDT/skylake-x.md, extras/kaslr-fix.md, troubleshooting/extended/kernel-issues.md
We figured this out here https://github.com/xCuri0/ReBarUEFI/issues/32. This motherboard needed patches to allocate in 64-bit range but some other HEDT motherboards will do it stock.
It turns out macOS gets stuck during PCI Configuration if any device is assigned above 44-bit (16TB) which is the default setting on many motherboards.
=> Add information about MMIOHBase on HEDT

installer-guide/linux-install.md, installer-guide/mac-install-recovery.md, installer-guide/windows-install.md
This PR adds macrecovery commands for macOS 14 Sonoma to the install guide pages for macOS, Linux and Windows. I used the `Mac-937A206F2EE63C01` BoardID which corresponds to MacBookPro15,1 (15-inch Mid 2018).
This change would affect the following locations:
1. https://dortania.github.io/OpenCore-Install-Guide/installer-guide/windows-install.html#downloading-macos
2. https://dortania.github.io/OpenCore-Install-Guide/installer-guide/linux-install.html#downloading-macos
3. https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install-recovery.html
Preview of proposed changes:
=> Add Sonoma macrecovery commands to the install guide
